# Generated by Django 3.0 on 2019-12-15 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('name', models.CharField(max_length=75, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('ip_location', models.CharField(max_length=50)),
                ('text_searched', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertiesOfSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.CharField(max_length=50, null=True)),
                ('published_from', models.DateTimeField(null=True)),
                ('published_to', models.DateTimeField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Category')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Countries')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Languages')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Query')),
            ],
        ),
        migrations.AddField(
            model_name='countries',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Languages'),
        ),
    ]
