# Generated by Django 3.0 on 2019-12-15 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191215_1609'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='languagescountry',
            unique_together={('languages', 'country')},
        ),
    ]
